# syntax=docker/dockerfile:1.7

# ─── stage 1: prune the monorepo ───────────────────────────────────────────
FROM node:22-alpine AS pruner
WORKDIR /app
RUN npm install -g turbo
COPY . .
# Using an env variable escapes Coolify's text replacement string mismatch
ENV TARGET_APP=@bookmi/api
RUN turbo prune ${TARGET_APP} --docker

# ─── stage 2: install all deps ─────────────────────────────────────────────
FROM node:22-alpine AS deps
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.15.0 --activate

# Copy only the pruned package.json files and the lockfiles
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# ─── stage 3: build ────────────────────────────────────────────────────────
FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.15.0 --activate

# Bring in the full source files generated by turbo prune
COPY --from=pruner /app/out/full/ .
COPY --from=deps /app/node_modules ./node_modules
COPY turbo.json ./

# Build dependencies and app automatically via Turborepo
ENV TARGET_APP=@bookmi/api
RUN pnpm --filter ${TARGET_APP} build

# Prune devDependencies from the workspace for runtime production
RUN pnpm --filter ${TARGET_APP} --prod deploy /app/pruned

# ─── stage 4: runtime ──────────────────────────────────────────────────────
FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4000

# curl for health probes; tini reaps zombies + forwards SIGTERM cleanly
RUN apk add --no-cache curl tini

# Only the compiled output + pruned prod node_modules
COPY --from=build /app/pruned/node_modules ./node_modules
COPY --from=build /app/apps/api/dist ./dist
# Migrations live inside dist after nest build copies them
COPY --from=build /app/apps/api/src/drizzle/migrations ./src/drizzle/migrations
COPY --from=build /app/apps/api/package.json ./package.json

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY docker/healthcheck.sh /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/entrypoint.sh /usr/local/bin/healthcheck.sh

# Non-root — Node's official image ships a `node` user (uid 1000)
USER node

EXPOSE 4000

HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
  CMD /usr/local/bin/healthcheck.sh

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/entrypoint.sh"]
